### PR TITLE
Merge master-dev branch to master

### PR DESCRIPTION
**Pull request by pengzhisun**

### CODE REVIEW

**Comment by feiskyer** [comment]
Huge changes here. Maybe merge the PR first and send PRs for new updates?

**Comment by andyzhangx** [comment]
@pengzhisun are we going to merge this PR first? And I have renamed this project to `container-service-for-azure-china`

**Comment by andyzhangx** [comment]
@feiskyer o, `master-dev` is the main branch now, we can go with `master-dev` branch from now. Just keep updating aks docs.

**Comment by andyzhangx** [comment]
@pengzhisun branch `master` should be obsolete, right?

**Pull request merged**
